/**
 * @project:        hotel-booking
 * @file:           Booking.h
 * @author(s):      Francesco Urbani <https://urbanij.github.io/>
 *
 * @date:           Mon Jul  1 12:43:37 CEST 2019
 * @Description:    stores booking data
 *
 */

#ifndef BOOKING_H
#define BOOKING_H


typedef struct booking {
    char    date[6];
    char    room[4];    
    char    code[6];    // alphanumeric, 5 char long, autogenerated
} Booking;


void printBooking(Booking* b){
    printf("Booking on date %s, in room %s, with code %s\n", 
            b->date, b->room, b->code
        );
    return;
}




#endif
