/**
 * @project:        hotel-booking
 * @file:           Booking.h
 * @author(s):      Francesco Urbani <https://urbanij.github.io/>
 *
 * @date:           Mon Jul  1 12:43:37 CEST 2019
 * @Description:    stores booking data
 *
 */

#ifndef BOOKING_H
#define BOOKING_H


typedef struct booking {
    char    date[6];
    int     room;    
    char    code[6];    // alphanumeric, 5 char long, autogenerated
} Booking;







#endif
